name: solar-protocol

services:
  datalogger:
    image: solar-protocol/datalogger
    build: ./datalogger
    restart: unless-stopped
    volumes:
      - data:/data
  api:
    image: solar-protocol/api
    build: ./api
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 11215:80
  protocol:
    image: solar-protocol/protocol
    build: ./protocol
    restart: unless-stopped
    command: python run.py now
    volumes:
      - data:/data
      - frontend:/frontend
      - local:/local
  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - data:/data
      - frontend:/frontend
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11221:80

volumes:
  data:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/data'
  frontend:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/frontend'
  local:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/local'
