version: '3'

services:
  charge-controller:
    image: charge-controller
    restart: always
    volumes:
      - data:/data
  api:
    image: nginx
    restart: always
    volumes:
      - data:/data
  web:
    image: nginx
    restart: always
    volumes:
      - data:/data
      - frontend:/frontend
      - ./nginx.conf:/etc/nginx/nginx.conf
  solar-protocol:
    image: solar-protocol
    restart: always
    volumes:
      - data:/data
      - frontend:/frontend

volumes:
  - data
  - frontend

