version: '3.7'

name: solar-protocol

services:
  api:
    restart: on-failure
    volumes:
      - ./api:/api
    command: python -m uvicorn api:app --proxy-headers --host 0.0.0.0 --port 80 --reload
  protocol:
    restart: on-failure
    command: python run.py now
    volumes:
      - ./protocol:/protocol
